### ISSUE TITLE
clean() choking on integers

### ISSUE THREAD

**Issue by DancingQuanta** [rafaqz/citation.vim#13]
The `clean()` function in `python/citation/zotero/parser` is choking on integers found in `issues`, `volumes` and `years`. What is this function for and should there be a type cast inside the function before the regexes?

**Comment by rafaqz** [comment]
Zotero fields can have html and other gunk in them that are generally removed in Zotero bibtex formatters like BibLatex.js, so I do the same to standardise output and avoid some formatting errors that occur otherwise. But I agree that function is a little vague as to it purpose, as are all of those string cleaning regex hacks, I'll reorganise and add some comments.

Unfortunately I can't reproduce the error, can you post the error output and your version of Zotero and python? Its likely a Zotero 4 issue as the database has changed in 5.0. I'll can try to fix by type casting everything.

I shamefully stopped testing against Zotero 4 after upgrading my setup to fix other issues, but unfortunately Zotero 5 just refuses to get out of beta.

**Comment by rafaqz** [comment]
Try the update
