### ISSUE TITLE
Manipulate zotero data

### ISSUE THREAD

**Issue by DancingQuanta** [rafaqz/citation.vim#14]
This request is a challenge. I wonder if it is possible to extend `citation.vim` to directly manipulate `zotero.sqlite` to add or remove items, edit fields, add notes etc like you are using `Zotero` app itself.
The first problem is with this is that data corruption may result from writing to `zotero.sqlite` if `Zotero` is running.

Other is that I don't know if `Unite.vim` allows this kind of functionality.

What do you think?

**Comment by rafaqz** [comment]
It would be great. My main use case is for editing and saving Zotero notes using the key to open a new buffer, but you could do the same for any field with the same code.

But there are two problems. Firstly sqlite dbs can only be accessed by one application at a time, and I often have zotero open when I work, and imagine many people do. The plugin currently copies the whole database to your temp directory so that it can open the copy while the main file is locked, so writing to it would achieve nothing unless you somehow know when to copy it back and are sure Zotero hasn't changed anything in the meantime (ie the ugliest of hacks - this plugin is already an hack, but at least a read-only hack). Second is Zotero has an api for saving data, but it is only for cloud data, not local data. at least at this stage. Basically whenever there is a sane way write local data I'll build it...

(Btw Unite just offers function hooks for supplying lists of strings (sources) and methods for acting on choices from them. This functionality wouldn't depend on those, just regular vimL.)

**Comment by DancingQuanta** [comment]
Would it be possible to detect if sqlite dbs is open with `psutil` where this module check if a file is opened by a process.
I am more interested in queueing edits to the db so that changes are made when possible but this code is a script not running program...

**Comment by rafaqz** [comment]
You could try something like that, but it would be an awful hack, that's really no what sqlite was designed to do and there are so many ways that will break. Better to wait for an api. Even better to help build the zotero local api.

**Comment by DancingQuanta** [comment]
Yes, a zotero local api would do. I don't know if LibZotero is a api though?
I wonder whether it is a good idea to close this issue, I feel that people may want to add their thoughts to this if  it is visible.

**Comment by rafaqz** [comment]
Zotero as an api for web. Not for local. We need one for local. 

Closed issues are searchable too. 
Cheers

**Comment by rafaqz** [comment]
This turns out to already work pretty easily using zotcli, no code required! This will add a note for the key under the cursor:

`nnoremap <silent><leader>cn :<C-u>UniteWithCursorWord -default-action=yank -force-immediately citation/title<cr><cr>:!zotcli add-note "<C-R>0"<cr>`
