### ISSUE TITLE
Opening files and urls - not recognized key-words

### ISSUE THREAD

**Issue by DerWeh** [rafaqz/citation.vim#9]
I am using `citation.vim` with `bibtex`:

```
let g:citation_vim_bibtex_file='~/citation/out.bib'                                                                                      
let g:citation_vim_mode='bibtex'
```

`out.bib` is generated via `pybtex-convert`.
The following sources don't display the specified information:

-citation/notes
-citation/file
-citation/url

For some sources `citation/url` displays the url, for most not, but in any case using the action `start` on them does nothing.

Can you for a start provide an sample `bibtex` file, to check if mine is simply setup wrong.

**Comment by rafaqz** [comment]
Hey nice catch, one char typo. I don't use this at all so haven't paid it enough attention (or written a test for it).

File opening should be working now. For me the color formatting hardly works for urls because they are so long they get cut in half, so the ones that are there might not be obvious. But if you have a citation that definitely has a url in the bibtex file that doesn't open with start, let me know - that would be another bug.

**Comment by rafaqz** [comment]
Ok so thats the url starting part at least. I'll have a look at the others. By displaying the file and notes where exactly do you mean? In the unite list or in the text output to yank/insert etc?

**Comment by rafaqz** [comment]
Files are printing and opening fine for me, paste some of your bibtex if they're actually not for you. 

Seems that notes will be missing if your bibtex uses 'annotation' instead of 'annote' ( why are there both???). And yes urls are broken for bibtex files with a separate file and url field. 

I'll fix both to work in both cases, thanks for being thorough in testing that!

**Comment by rafaqz** [comment]
Ok that should all work now. Let me know anything else. This plugin really needs a thorough test suite but having bibtex/biblatex/zotero4/zotero5 inputs with so many fields there are a lot of things out of my control and more tests to write than I have time for...
